### ISSUE TITLE
Add an easily customizable TOC

### ISSUE THREAD

**Issue by dlesnoff** [nimib-land/nimibex#13]
In the few Nimib files that I created, I always resort to templates similar to this one for the creation of a table of contents (TOC):
```nim
var nbToc: NbBlock

template addToc =
  newNbBlock("nbText", false, nb, nbToc, ""):
    nbToc.output = "### Table of Contents:\n\n"

template nbSection(name:string) =
  let anchorName = name.toLower.replace(" ", "-")
  nbText "<a name = \"" & anchorName & "\"></a>\n## " & name & "\n\n---"
  # see below, but any number works for a numbered list
  nbToc.output.add "1. <a href=\"#" & anchorName & "\">" & name & "</a>\n"
```
It would be interesting to make this easily configurable with a simple addToc command, that would define nbSection, nbSubSection, nbSubSubSection, nbParagraph (like Latex?) or nbH1Title, nbH2Title, etc ... for each level of heading.
It would be cool if the Toc appearance could be configurable too (level of heading, title?) without having to resort to nbToc.output and newNbBlock.

**Comment by pietroppeter** [comment]
The idea was to add this to nimib itself, see https://github.com/pietroppeter/nimib/issues/58
